---
# Machine specific software
software:
  - autorandr

# Configure audio & bluetooth
audio: false

# Include software specific tasks
aur: true
docker: true
dunst: true
firefox: true
git: true
i3: true
libvirt: true
mpd: true
mpv: true
ncmpcpp: true
neofetch: true
newsboat: true
neovim: true
ranger: true
suckless: true
tmux: true
zathura: true
zsh: true
