---
- name: Installation play
  tags: install
  hosts: all
  remote_user: root

  pre_tasks:
    - name: End the play if host is not booted from Arch Linux ISO
      meta: end_host
      when: ansible_facts.cmdline.archisolabel is not defined

    - name: Verify the UEFI boot mode
      stat:
        path: /sys/firmware/efi/efivars
      register: efivars
      failed_when: efivars.stat.isdir is not defined

    - name: Check internet connection
      command: ping -c 1 -w 1 google.com
      changed_when: False

  roles:
    - install

  post_tasks:
    - name: Reboot after installation is complete
      shell: sleep 2 && reboot
      async: 5
      poll: 0
    - meta: end_host

- name: Post-installation play
  hosts: all
  remote_user: test
  gather_facts: no

  pre_tasks:
    - name: Wait one minute for connection
      wait_for_connection:
        timeout: 60
        delay: 5

    - name: Check internet connection
      command: ping -c 1 -w 1 google.com
      changed_when: False

  roles:
    - { role: post-install, tags: post-install }
    - { role: hardening, tags: hardening }
    - { role: blackarch, tags: blackarch }

  post_tasks:
    - name: Reboot after installation is complete
      become: yes
      shell: sleep 5 && reboot
      async: 5
      poll: 0

    - name: Disable ssh daemon
      become: yes
      systemd:
        name: sshd
        enabled: no
      async: 5
      poll: 0
    - meta: end_host
