# TODO: add tasks for configuration inside of the kvm libvirt machine (check spice-vdagent for clipboard sharing)
---
- hosts: workstations
  remote_user: test

  vars:
    # Keyboard settings
    country: PL
   
    # Copy user data from the ansible controller
    migrate: false

    # Self explanatory
    aur_helper: yay

    # Include software specific tasks
    aur: false
    docker: false
    dunst: false
    firefox: false
    git: false
    i3: false
    libvirt: false
    mpd: false
    mpv: false
    ncmpcpp: false
    neofetch: false
    newsboat: false
    neovim: false
    ranger: false
    suckless: false
    tmux: false
    zathura: false
    zsh: true

  pre_tasks:
    - name: Check internet connection
      command: ping -c 1 -w 1 google.com
      changed_when: False

  roles:
    - dotfiles
  
      # post_tasks:
      #    - name: Reboot after installation is complete
      #      become: yes
      #      shell: sleep 2 && reboot
      #      async: 5
      #      poll: 0
      #    - meta: end_host
