---
- hosts: workstations
  remote_user: test

  vars:
    # Path for the repository and dotfiles
    repo_path: '{{ ansible_env.HOME }}/repos/'
    dotfiles_path: '{{ repo_path }}/archsible/roles/dotfiles/files'

    # Setup blackarch repository
    blackarch: true

    # Include individual dotfiles
    dunst: true
    docker: true
    firefox: true
    i3: true
    mpd: true
    mpv: false
    ncmpcpp: true
    neofetch: true
    newsboat: true
    neovim: true
    ranger: true
    suckless: true
    tmux: true
    zathura: false
    zsh: true

  pre_tasks:
    - name: Check internet connection
      command: ping -c 1 -w 1 google.com
      changed_when: False

  roles:
    - dotfiles
  
#  post_tasks:
#    - name: Reboot after installation is complete
#      become: yes
#      shell: sleep 2 && reboot
#      async: 5
#      poll: 0
#    - meta: end_host
