---
- hosts: workstations
  remote_user: test

  vars:
    # Copy user data from the ansible controller
    migrate: false

    # Self explanatory
    aur_helper: yay

    # Include software specific tasks
    aur: false
    docker: false
    dunst: false
    firefox: false
    git: true
    i3: false
    mpd: false
    mpv: false
    ncmpcpp: false
    neofetch: false
    newsboat: false
    neovim: true
    ranger: false
    suckless: false
    tmux: false
    zathura: false
    zsh: false

  pre_tasks:
    - name: Check internet connection
      command: ping -c 1 -w 1 google.com
      changed_when: False

  roles:
    - dotfiles
  
      #  post_tasks:
      #     - name: Disable sshd.service
      #       become: yes
      #       systemd:
      #         name: sshd
      #         enabled: no
      #
      #     - name: Reboot after installation is complete
      #       become: yes
      #       shell: sleep 2 && reboot
      #       async: 5
      #       poll: 0
      #     - meta: end_host
