# TODO: checkout coreutils improvements / alternatives from archwiki - saerch for wechiwiki core utilities
# TODO: checkout base9 from suckless and explore possibilities of using it along / instead of coreustils GNU
---
- hosts: workstations
  remote_user: test

  vars:
    # Copy environment from the ansible controller
    # TODO: add file to track all files for migration task
    migrate: false

    # Self explanatory
    aur_helper: yay

    # Include software tasks
    aur: false
    docker: false
    dunst: false
    firefox: true # TODO: add symlinks for user.js 
    git: false
    i3: true
    mpd: false
    mpv: false
    ncmpcpp: false
    neofetch: false
    newsboat: false
    neovim: false
    ranger: false
    suckless: false
    tmux: false
    zathura: true
    zsh: true

  pre_tasks:
    - name: Check internet connection
      command: ping -c 1 -w 1 google.com
      changed_when: False

  roles:
    - dotfiles
  
      #  post_tasks:
      #     - name: Disable sshd.service
      #       become: yes
      #       systemd:
      #         name: sshd
      #         enabled: no
      #
      #     - name: Reboot after installation is complete
      #       become: yes
      #       shell: sleep 2 && reboot
      #       async: 5
      #       poll: 0
      #     - meta: end_host
