---
- hosts: workstations
  remote_user: test

  vars:
    # Path for the repository and dotfiles
    repo_path: '{{ ansible_env.HOME }}/repos/'
    dotfiles_path: '{{ repo_path }}/archsible/roles/dotfiles/files'

    # Setup blackarch repository
    blackarch: false # TODO: needs fix

    # Include individual dotfiles
    dunst: false
    docker: false
    firefox: true
    i3: true
    mpd: false
    mpv: false
    ncmpcpp: false
    neofetch: false
    newsboat: false
    neovim: false
    ranger: false
    suckless: false
    tmux: false
    zathura: false
    zsh: true

  pre_tasks:
    - name: Check internet connection
      command: ping -c 1 -w 1 google.com
      changed_when: False

  roles:
    - dotfiles
  
#  post_tasks:
#    - name: Reboot after installation is complete
#      become: yes
#      shell: sleep 2 && reboot
#      async: 5
#      poll: 0
#    - meta: end_host
