# TODO: add task to install qemu-guest-agent on virtual machines (guests) (and enable the service)
---
- hosts: workstations
  remote_user: root
  vars:
    # Mirrorlist country code
    country: PL

    # Block devices selection and size
    install_drive: nvme0n1
    root_size: 30G
    var_size: 10G
    varlog_size: 5G
    vartmp_size: 2G

    # Set to true if you want to overwrite disk with random data before installation
    shred: false

    # Configure wireless adapter
    wireless: true
    wireless_utility: iwd

    # Passwords & user configuration
    luks_password: test
    root_password: test

    user_username: test
    user_password: test

  pre_tasks:
    - name: Verify the UEFI boot mode
      stat:
        path: /sys/firmware/efi/efivars
      register: efivars
      failed_when: efivars.stat.isdir is not defined

    - name: Check internet connection
      command: ping -c 1 -w 1 google.com
      changed_when: False

  roles:
    - install
  
  post_tasks:
    - name: Reboot after installation is complete
      shell: sleep 2 && reboot
      async: 5
      poll: 0
    - meta: end_host
