# TODO: add task to install qemu-guest-agent on virtual machines (guests) (and enable the service)
---
- hosts: workstations
  remote_user: root
  vars:
    # Overwrite disk with random data before installation
    shred: false

    # Mirrorlist country code
    country: PL

      # TODO: check whether swap is needed on vm and if not include the conditional
    # Partitions size
    root_size: 50G
    var_size: 10G
    varlog_size: 5G
    vartmp_size: 2G

    # Passwords & user configuration
    luks_password: test
    root_password: test

    user_username: test
    user_password: test

  pre_tasks:
    - name: Verify the UEFI boot mode
      stat:
        path: /sys/firmware/efi/efivars
      register: efivars
      failed_when: efivars.stat.isdir is not defined

    - name: Check internet connection
      command: ping -c 1 -w 1 google.com
      changed_when: False

  roles:
    - install
  
  post_tasks:
    - name: Reboot after installation is complete
      shell: sleep 2 && reboot
      async: 5
      poll: 0
    - meta: end_host
