---
- hosts: workstations
  remote_user: root
  vars:
    # Mirrorlist country code
    country: PL

    # Processor vendor [intel / amd]
    proc: intel

    # Drive to which the system will be installed
    drive: nvme0n1

    # Network interfaces
    wired_adapter: true
    wireless_adapter: true

    # Password configuration
    luks_password: test
    root_password: test

  pre_tasks:
    - name: Verify the UEFI boot mode
      stat:
        path: /sys/firmware/efi/efivars
      register: efivars
      failed_when: efivars.stat.isdir is not defined

    - name: Check internet connection
      command: ping -c 1 -w 1 google.com
      changed_when: False

# TODO: Remove after implementing shred task
    - name: Remove existing data
      block:
        - name: Remove the volume group and physical volume
          lvg:
            vg: vg
            pvs: /dev/mapper/cryptlvm
            state: absent
            force: yes
    
        - name: Remove the LUKS container
          luks_device:
            name: cryptlvm
            state: absent
    
        - name: Erase GPT structures from the disk
          command: sgdisk -Z '/dev/{{ drive }}'

  roles:
    - install
  
  post_tasks:
    - name: Reboot after installation is complete
      shell: sleep 2 && reboot
      async: 5
      poll: 0
    - meta: end_host
