---
- hosts: workstations
  remote_user: root
  vars:
    # Include hardening tasks
    hardening: false

    # Localization Settings
    region: Europe
    country: PL
    city: Warsaw

    # Self explanatory
    hostname: TEST
    user_username: test
    user_password: test

  pre_tasks:
    - name: Check internet connection
      command: ping -c 1 -w 1 google.com
      changed_when: False

  roles:
    - post-install

  post_tasks:
    - name: Import the hardening role
      import_role:
        name: hardening
      when: hardening
  
    # TODO: move to dotfiles
    - name: Disable sshd.service
      systemd:
        name: sshd
        enabled: no

          # - name: Reboot after installation is complete
          #   shell: sleep 2 && reboot
          #   async: 5
          #   poll: 0
          # - meta: end_host
