---
- hosts: workstations
  remote_user: root
  vars:
    # Timezone and locale configuration
    region: Europe
    country: PL
    city: Warsaw

    # GPU manufacturer (intel / amd / nvidia)
    #gpu: intel

    # Self explanatory
    hostname: TEST
    user_username: test
    user_password: test

  pre_tasks:
    - name: Check internet connection
      command: ping -c 1 -w 1 google.com
      changed_when: False

  roles:
    - post-install
  
      # post_tasks:
      #   - name: Reboot after installation is complete
      #     shell: sleep 2 && reboot
      #     async: 5
      #     poll: 0
      #   - meta: end_host
