- name: Docker - Install packages
  become: yes
  pacman:
    name: 
      - docker
      - docker-compose
    state: present

- name: Docker - Add user to docker group
  become: yes
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
