- name: i3 - Install packages
  become: yes
  package:
    name:
      - i3-gaps
      - i3blocks
      - noto-fonts
      - ttf-joypixels
      - ttf-font-awesome
      - ttf-dejavu
      - ttf-inconsolata
      - ttf-liberation
    state: present

- name: i3 - Symlink configuration
  file:
    src:  "{{ dotfiles_path }}/i3"
    path: "~/.config/i3"
    state: link
