# TODO: fix sb makefiles to cleanup after installation
# TODO: check docker setup

# TODO: check if there is a difference between linking directory and linking all files inside directory in a loop
# TODO: compare files in repo with currently used on desktop and update if necessary

- name: Workspace setup
  block:
    - name: Create workspace directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "~/.cache"
        - "~/.config"
        - "~/.local"
        - "~/ctf"
        - "~/downloads"
        - "~/fieldwork"
        - "~/music"
        - "~/pictures"
        - "{{ repo_path }}"
        - "~/tmp"
        - "~/videos"
    
    - name: Clone archsible repository
      git:
        repo: https://github.com/baj0k/archsible.git
        dest: '{{ repo_path }}/archsible'

    - name: Symlink user-dirs.dirs
      file:
        src: "{{ dotfiles_path }}/user-dirs.dirs"
        path: "~/.config/user-dirs.dirs"
        state: link
    
    - name: User - Symlink locale.conf
      file:
        src: "{{ dotfiles_path }}/locale.conf"
        path: "~/.config/locale.conf"
        state: link
    
    - name: User - Symlink local scripts
      file:
        src: "{{ dotfiles_path }}/bin"
        path: "~/.local/bin"
        state: link

- name: Include conditional tasks - System
  include_tasks: '{{ item.tasks }}'
  when: item.when
  loop:
    - { tasks: blackarch.yml, when: '{{ blackarch }}' }

- name: Include conditional tasks - Software
  include_tasks: '{{ item.tasks }}'
  when: item.when
  loop:
    - { tasks: dunst.yml, when: '{{ dunst }}' }
    - { tasks: docker.yml, when: '{{ docker }}' }
    - { tasks: firefox.yml, when: '{{ firefox }}' }
    - { tasks: i3.yml, when: '{{ i3 }}' }
    - { tasks: mpd.yml, when: '{{ mpd }}' }
    - { tasks: mpv.yml, when: '{{ mpv }}' }
    - { tasks: ncmpcpp.yml, when: '{{ ncmpcpp }}' }
    - { tasks: neofetch.yml, when: '{{ neofetch }}' } # TODO: consider removing
    - { tasks: newsboat.yml, when: '{{ newsboat }}' } # TODO: cleanup urls
    - { tasks: neovim.yml, when: '{{ neovim }}' }   # TODO: Check plugins (fix the healthcheck provider issue)
    - { tasks: ranger.yml, when: '{{ ranger }}' }   # TODO: update configuration files, use: ranger --copy-config all
    - { tasks: suckless.yml, when: '{{ suckless }}' }
    - { tasks: tmux.yml, when: '{{ tmux }}' }
    - { tasks: xorg.yml, when: '{{ i3 }}' }
    - { tasks: zathura.yml, when: '{{ zathura }}' }
    - { tasks: zsh.yml, when: '{{ zsh }}' }

      # TODO: add crontab task (checkout if systemd timers are better)
