# TODO: fix sb makefiles to cleanup after installation
# TODO: check docker setup


- name: Workspace setup
  block:
    - name: Create workspace directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "~/.cache"
        - "~/.config"
        - "~/.local"
        - "~/ctf"
        - "~/downloads"
        - "~/fieldwork"
        - "~/music"
        - "~/pictures"
        - "~/repos"
        - "~/tmp"
        - "~/videos"
    
    - name: Clone archsible repository
      git:
        repo: https://github.com/baj0k/archsible.git
        dest: ~/repos/archsible

          #- name: Symlink user-dirs.dirs
          #  file:
          #    src: "{{ ansible_env.PWD }}/files/user-dirs.dirs"
          #    path: "~/.config/user-dirs.dirs"
          #    state: link
          #
          #- name: User - Symlink locale.conf
          #  file:
          #    src: "{{ ansible_env.PWD }}/files/locale.conf"
          #    path: "~/.config/locale.conf"
          #    state: link
          #
          #- name: User - Symlink local scripts
          #  file:
          #    src: "{{ ansible_env.PWD }}/files/bin"
          #    path: "~/.local/bin"
          #    state: link
    
#- include: abook.yml
#  when: abook
#
#- include: dunst.yml
#  when: dunst
#
#- include: docker.yml
#  when: dunst
#
#- include: firefox.yml
#  when: firefox
#
#- include: i3.yml
#  when: i3
#
#- include: mpd.yml
#  when: mpd
#
#- include: mpv.yml
#  when: mpv
#
#- include: mutt.yml
#  when: mutt
#
#- include: ncmpcpp.yml
#  when: ncmpcpp
#
#- include: neofetch.yml
#  when: neofetch
#
#- include: newsboat.yml
#  when: newsboat
#
- name: Import tasks based on playbook variables
  import_tasks: neovim.yml
  when: neovim
#
#- include: ranger.yml
#  when: ranger
#
#- include: suckless.yml
#  when: suckless
#
#- include: tmux.yml
#  when: tmux
#
#- include: zathura.yml
#  when: zathura
#
#- include: zsh.yml
#  when: zsh
#
