- name: Neovim - Install packages
  become: yes
  pacman:
    name: 
      - neovim
    state: present

- name: Neovim - Create directories
  file:
    path: "~/.config/nvim"
    state: directory

- name: Neovim - Symlink configuration
  file:
    src:  "{{ dotfiles_path }}/nvim/init.vim"
    path: "~/.config/nvim/init.vim"
    state: link
