- name: Symlink user-dirs.dirs
  file:
    src: "{{ dotfiles_path }}/user-dirs.dirs"
    path: "~/.config/user-dirs.dirs"
    state: link

- name: Symlink locale.conf
  file:
    src: "{{ dotfiles_path }}/locale.conf"
    path: "~/.config/locale.conf"
    state: link

- name: Symlink local scripts
  file:
    src: "{{ dotfiles_path }}/bin"
    path: "~/.local/bin"
    state: link

# TODO: consider adding a variable or moving wallpapers to a repository
- name: Copy wallpapers
  copy:
    src: ~/pictures/wallpaper
    dest: ~/pictures/
  when: migrate
