- name: Xorg - Install packages
  become: yes
  package:
    name: 
      - xorg
      - xorg-xinit
      - xwallpaper
      - xcompmgr
    state: present

- name: Xorg - Symlink configuration
  file:
    src: "{{ ansible_env.PWD }}/files/xorg"
    path: "~/.config/xorg"
    state: link
