- name: Zathura - Install packages
  become: yes
  pacman:
    name: 
      - zathura
      - zathura-pdf-mupdf
    state: present

- name: Zathura - Symlink configuration
  file:
    src:  "{{ dotfiles_path }}/zathura"
    path: "~/.config/zathura"
    state: link
