- name: Zsh - Install packages
  become: yes
  package:
    name:
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting
    state: present

- name: Zsh - Change default shell
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh

- name: Zsh - Workaround for XDG compliance
  become: yes
  lineinfile:
    path: /etc/zsh/zshenv
    state: present
    create: yes
    line: 'export ZDOTDIR="$HOME/.config/zsh"'

- name: Zsh - Symlink configuration
  file:
    src:  "{{ dotfiles_path }}/zsh"
    path: "~/.config/zsh"
    state: link
