# System configuration
install: true
system: false
user: false
aur: false
blackarch: false
bluetooth: false

bluetooth_dongle: true

# Software configuration
abook: false
dunst: false
docker: false
firefox: false
i3: false
mpd: false
mpv: false
mutt: false
ncmpcpp: false
neofetch: false
newsboat: false
nvim: false
ranger: false
suckless: false
tmux: false
zathura: false
zsh: false
