---
- name: Download blackarch setup script
  get_url:
    url: https://blackarch.org/strap.sh
    dest: /tmp/strap.sh
    
- name: Setup blackarch repository
  become: yes
  command: "sh /tmp/strap.sh"

- name: Install blackarch packages
  become: yes
  pacman:
    name:
      - burpsuite
      - jre-openjdk
      - gobuster
      - nmap
      - metasploit
      - msf-mpc
      - gnu-netcat
      - rlwrap
      - openvpn
    state: present

- name: Clone SecLists repository
  git:
    repo: https://github.com/danielmiessler/SecLists.git
    dest: "{{ ansible_env.HOME }}/.local/share/wordlists"
    depth: 1
