---
- name: Gather facts
  setup:

- name: Download blackarch setup script
  get_url:
    url: https://blackarch.org/strap.sh
    dest: /tmp/strap.sh
    
- name: Setup blackarch repository
  become: yes
  command: "/bin/sh /tmp/strap.sh"

- name: Setup blackarch mirrorlist
  become: yes
  lineinfile:
    dest: /etc/pacman.d/blackarch-mirrorlist
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  loop:
    - {regexp: 'Server = https://ftp.halifax.rwth-aachen.de(.*)$', line: '#Server = https://ftp.halifax.rwth-aachen.de(.*)$' }
    - {regexp: 'Server = https://ftp.icm.edu.pl(.*)$', line: 'Server = https://ftp.icm.edu.pl\1' }

- name: Install blackarch packages
  become: yes
  pacman:
    name:
      - burpsuite
      - gnu-netcat
      - gobuster
      - hexedit
      - hydra
      - john
      - jre11-openjdk
      - mariadb-clients
      - metasploit
      - msf-mpc
      - nikto
      - nmap
      - nuclei
      - openvpn
      - postgresql
      - rlwrap
      - seclists
      - smbclient
      - sqlmap
      - tcpdump
      - wpscan
    state: present

- name: Download firefox extensions
  become: yes
  get_url:
    url: "https://addons.mozilla.org/firefox/downloads/latest/{{ item.name }}/latest.xpi"
    dest: "/usr/lib/firefox/browser/extensions/{{ item.id }}.xpi"
  loop_control:
    index_var: loop_index
  loop:
    - { name: foxyproxy-standard, id: foxyproxy@eric.h.jung }
    - { name: wappalyzer, id: wappalyzer@crunchlabz.com }
