---
- name: Download blackarch setup script
  get_url:
    url: https://blackarch.org/strap.sh
    dest: /tmp/strap.sh
    
- name: Setup blackarch repository
  become: yes
  command: "sh /tmp/strap.sh"

- name: Install blackarch packages
  become: yes
  pacman:
    name:
      - burpsuite
      - gnu-netcat
      - gobuster
      - jre-openjdk
      - metasploit
      - msf-mpc
      - nmap
      - openvpn
      - rlwrap
      - seclists
    state: present

