#!/bin/sh

# Source Xresources
xrdb -merge $XDG_CONFIG_HOME/xorg/Xresources &

# Autostart 
autorandr --change &
crond -f "$XDG_CONFIG_HOME/crontab" &
redshift -P -O 4200 &
remap &
xset s off -dpms &
xcompmgr &

birdtray &
blueman-applet &
dunst &
firefox &
mpd &

caprine --minimize &
discord --start-minimized &
signal-desktop --start-in-tray &

exec i3 
