# TODO: fix sb makefiles to cleanup after installation
# TODO: check docker setup
#
# TODO: If any problems with the time occur, try timedatectl set-local-rtc 0 and set-ntp 1
# TODO: remove tags
        #- include: system/system.yml
        #  when: post-install
        #  become: yes
    
          #- include: system/blackarch.yml
          #  when: blackarch
          #
          #- include: system/bluetooth.yml
          #  when: bluetooth
          #
          #- include: docker.yml
          #  when: dunst
          #
          #- include: suckless.yml
          #  when: suckless
- name: Pacman configuration
  become: yes
  block:
    # TODO: rankmirrors
    - name: Download mirrorlist
      get_url:
        url: 'https://archlinux.org/mirrorlist/?country={{ country }}&ip_version=4&protocol=https&use_mirror_status=on'
        dest: /etc/pacman.d/mirrorlist
        force: yes
    
    - name: Uncomment mirrors
      replace:
        path: /etc/pacman.d/mirrorlist
        regexp: '##.*\n#Server'
        replace: 'Server'
    
    - name: Change configuration file
      lineinfile:
        dest: /etc/pacman.conf
        regexp: '{{ item.regex }}'
        line: '{{ item.line }}'
        insertafter: '{{ item.insertafter }}'
      loop:
        - {regex: Architecture, line: Architecture = x86_64, insertafter: }
        - {regex: Color, line: Color, insertafter: }
        - {regex: ParallelDownloads, line: ParallelDownloads = 5, insertafter: }
        - {regex: '^#\[multilib\]$', line: '[multilib]', insertafter: }
        - {regex: Include = /etc/pacman.d/mirrorlist, line: Include = /etc/pacman.d/mirrorlist, insertafter: [multilib] }

    - name: Update system
      pacman:
        update_cache: yes
        upgrade: yes
    
    - name: Install packages
      tags: long
      package:
        name:
          - git
          # TODO: is acpi needed on desktop or laptop only?
          - acpi
          - bat
          - wget
          - rsync
          - man-db
          - man-pages
          - base-devel
          - dash
          # fonts TODO: test whether all below fonts are needed / additional are needed
          - noto-fonts
          - ttf-inconsolata
          - ttf-liberation
          - ttf-joypixels
          - ttf-dejavu
          - ttf-font-awesome
        state: present
    
          #- name: AUR - Install AUR packages
          #  become: no
          #  aur:
          #    name: 
          #      - pikaur
          #      - neovim-git
          #      - girara-git
          #      - zathura-git
          #    use: makepkg
          #    state: present
          #  when: aur

- name: User configuration
  block:
    # TODO: check if all the groups are necessary / need to add more
    - name: Add user to groups
      become: yes
      user:
        name: "{{ ansible_user_id }}"
        groups:
          - adm
          - games
          - audio
          - http
          - sys
          - wheel
          - kvm
          - video
        append: yes

    - name: User - Create workspace directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "~/.cache"
        - "~/.config"
        - "~/.local"
        - "~/ctf"
        - "~/downloads"
        - "~/fieldwork"
        - "~/music"
        - "~/pictures"
        - "~/repos"
        - "~/tmp"
        - "~/videos"
    
