# TODO: optimal mirror selection task is temporary, mirrorlist should be generated on post-configuration playbook after reboot with: reflector --fastest 5 --country Poland --age 12 --protocol https --sort rate --ipv4
# TODO: optimal mirror selection should be done periodically (after reboot?) (https://wiki.archlinux.org/title/Systemd/Timers)
# TODO: optimal mirror selection for blackarch repositories: rankmirrors -t /etc/pacman.d/blackarch-mirrorlist -r blackarch (remove -t option after manually ranking the mirrors)
#
- name: Network - Setup DNS
  lineinfile:
    path: /etc/resolv.conf
    line: nameserver 1.1.1.1
    state: present

