- name: User - Add user
  become: yes
  user:
    name: "{{ username }}"
    groups: 
      - adm
      - games
      - audio
      - http
      - sys
      - wheel
      - kvm
      - video
    append: yes
    password: "{{ password | password_hash('sha512') }}"
    update_password: on_create

- name: User - Sudoers NOPASSWD for the wheel group.
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '%wheel ALL='
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
