- name: Localization settings
  block:
    - name: Set timezone
      timezone:
        name: '{{ region }}/{{ city }}'
        hwclock: local

    - name: Remove unnecessary lines from locale.gen file
      lineinfile:
        path: /etc/locale.gen
        regexp: "#\\s+"
        state: absent

    - name: Generate locales
      locale_gen:
        name: '{{ item }}'
      loop:
        - en_US.UTF-8
        - "{{ country|lower + '_' + country + '.UTF-8' }}"

    - name: Create locale.conf
      lineinfile:
        create: yes
        path: /etc/locale.conf
        regexp: LANG=en_US\.UTF-8
        line: LANG=en_US.UTF-8
    
    - name: Create vconsole.conf
      blockinfile:
        create: yes
        path: /etc/vconsole.conf
        block: |
          KEYMAP={{ country|lower }}
          FONT=Lat2-Terminus16
          FONT_MAP=8859-2

    - name: Set a hostname
      hostname:
        name: '{{ hostname }}'

- name: User configuration
  block:
    - name: Create user
      user:
        name: "{{ user_username }}"
        groups:
          - adm
          - games
          - sys
          - wheel
          - lp
          - audio
          - kvm
          - video
        append: yes
        password: "{{ user_password | password_hash('sha512') }}"
        update_password: on_create

    - name: Give passwordless sudo access to the wheel group
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '%wheel ALL='
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo --check --file=%s'

- name: Package management
  block:
    - name: Install reflector
      package:
        name:
          - reflector

    - name: Configure reflector
      lineinfile:
        path: /etc/xdg/reflector/reflector.conf
        regexp: '{{ item.regex }}'
        line: '{{ item.line }}'
      loop:
        - {regex: "^#*\\s*--country", line: "{{ '--country ' + country|lower }}" }
        - {regex: "^#*\\s*--protocol", line: "--protocol https" }
        - {regex: "^#*\\s*--sort", line: "--sort rate" }

    - name: Rank mirrors
      systemd:
        name: reflector
        state: started

    - name: Enabel multilib repository and change pacman configuration options
      lineinfile:
        dest: /etc/pacman.conf
        regexp: '{{ item.regex }}'
        line: '{{ item.line }}'
        insertafter: '{{ item.insertafter }}'
      loop:
        - {regex: Architecture, line: Architecture = x86_64, insertafter: }
        - {regex: Color, line: Color, insertafter: }
        - {regex: ILoveCandy, line: ILoveCandy, insertafter: Color}
        - {regex: ParallelDownloads, line: ParallelDownloads = 5, insertafter: }
        - {regex: NoExtract, line: NoExtract = mirrorlist.pacnew, insertafter: }
        - {regex: '^#\[multilib\]$', line: '[multilib]', insertafter: }
        - {regex: Include = /etc/pacman.d/mirrorlist, line: Include = /etc/pacman.d/mirrorlist, insertafter: [multilib] }

    - name: Update system
      pacman:
        update_cache: yes
        upgrade: yes
    
    - name: Install packages
      package:
        name:
          - git
          - wget
          - rsync
          - man-db
          - man-pages
          - base-devel
          - pkgfile
        state: present

    - name: Synchronize pkgfile database
      systemd:
        name: pkgfile-update
        state: started

- name: Systemd configuration
  block:
    - name: Enable service timer units
      systemd:
        name: '{{ item }}'
        enabled: yes
      loop:
        - reflector.timer
        - pkgfile-update.timer
