- name: install neovim
  package:
    name:
      - neovim
    state: present

- name: symlink dotfiles
  file:
    src: "{{ ansible_env.PWD }}/roles/nvim/files/init.vim"
    path: "{{ ansible_env.PWD }}/.config/nvim/init.vim"
    state: link
