- name: install neovim
  become: yes
  package:
    name: 
      - neovim
    state: present

- name: symlink dotfiles
  file:
    src: "{{ ansible_env.PWD }}/roles/nvim/files/init.vim"
    path: "~/.config/nvim/init.vim"
    state: link
